### ISSUE TITLE
Notifications for Comments and @Mentions

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#70] opened 2022-07-14 00:51 UTC
If someone @ mentions my name or comments on my post I want a new notification.

**Comment by mesosoi** [comment] 2022-07-14 01:39
> If someone @ mentions my name or comments on my post I want a new notification.

A duplicate of https://github.com/mesosoi/silverwaregames-io-issue-tracker/issues/8 perhaps?

**Closed** 2023-01-17 10:10 UTC
Labels: duplicate, enhancement
